Update eks-deployment-appointment.yml

diff --git a/.github/workflows/eks-deployment-appointment.yml b/.github/workflows/eks-deployment-appointment.yml
--- a/.github/workflows/eks-deployment-appointment.yml
+++ b/.github/workflows/eks-deployment-appointment.yml
@@ -47,9 +47,13 @@ jobs:
         run: |
           IMAGE_TAG="appointment-service"
           ECR_REPO="183295407444.dkr.ecr.us-east-1.amazonaws.com/meditrack"
-          
-          # Navigate to the YAML directory
-          cd ../ymal
+
+          # Ensure the correct directory path
+          if [ -d "../yaml" ]; then
+            cd ../yaml
+          else
+            echo "YAML directory not found. Check your repository structure." && exit 1
+          fi
 
           # Apply the deployment changes for appointment service
           kubectl set image deployment/appointment-service appointment-service=$ECR_REPO:$IMAGE_TAG --kubeconfig=${{ secrets.KUBECONFIG }}
